import type { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body>
        <div
          className="max-w-[600px] m-auto min-h-[100dvh]"
          style={{
            backgroundImage: 'url(/images/paper-texture.svg)',
            filter: 'brightness(1.05)',
          }}
        >
          {children}
        </div>
      </body>
    </html>
  )
}

export default RootLayout
